<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>rowiff.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="rowiff.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CoreCLR-NCalc" Version="3.1.253" />
  </ItemGroup>

</Project>